/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/admin/api/acl/invalidate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Acl Invalidate
         * @description The ADR-004 invalidation hook. Call on any membership change, either direction.
         */
        post: operations["invalidateAcl"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/api/connectors": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Connectors */
        get: operations["listConnectors"];
        put?: never;
        /** Create Connector */
        post: operations["createConnector"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/api/connectors/{name}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Connector */
        delete: operations["deleteConnector"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/api/connectors/{name}/ingest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Ingest Connector */
        post: operations["ingestConnector"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/api/index": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Index Health */
        get: operations["indexHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/api/simulate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Simulate
         * @description Preview the corpus as any principal: what they would see, and why.
         */
        post: operations["simulate"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AclCacheView */
        AclCacheView: {
            /** Errors */
            errors: number;
            /** Evictions */
            evictions: number;
            /** Hits */
            hits: number;
            /** Misses */
            misses: number;
            /** Size */
            size: number;
            /** Ttl Seconds */
            ttl_seconds: number;
        };
        /** AclInvalidate */
        AclInvalidate: {
            /**
             * All
             * @default false
             */
            all?: boolean;
            /** Group */
            group?: string | null;
            /** Principal */
            principal?: string | null;
        };
        /** ConnectorCreate */
        ConnectorCreate: {
            /**
             * Kind
             * @enum {string}
             */
            kind: "filesystem" | "gdrive";
            /** Name */
            name: string;
            /** Root */
            root?: string | null;
        };
        /** ConnectorView */
        ConnectorView: {
            /**
             * Kind
             * @enum {string}
             */
            kind: "filesystem" | "gdrive";
            last_run: components["schemas"]["IngestRunView"] | null;
            /** Name */
            name: string;
            /** Needs Request Token */
            needs_request_token: boolean;
            /** Root */
            root: string | null;
        };
        /** DocumentDecision */
        DocumentDecision: {
            /** Connector */
            connector: string;
            /** Denies */
            denies: string[];
            /** Grants */
            grants: string[];
            /** Id */
            id: string;
            /** Reason */
            reason: string;
            /** Title */
            title: string;
            /** Uri */
            uri: string;
            /** Visible */
            visible: boolean;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** Health */
        Health: {
            /** Chunks */
            chunks: number;
            /** Documents */
            documents: number;
            /** Embedder */
            embedder: string;
            /** Index Size */
            index_size: number;
            /** Reranker */
            reranker: string;
            /** Status */
            status: string;
            /** Store */
            store: string;
            /** Version */
            version: string;
        };
        /** IndexHealth */
        IndexHealth: {
            acl_cache: components["schemas"]["AclCacheView"];
            /** Acl Principals */
            acl_principals: number;
            /** Bytes On Disk */
            bytes_on_disk: number;
            /** Bytes Per Chunk */
            bytes_per_chunk: number;
            /** Chunks */
            chunks: number;
            /** Dimension */
            dimension: number;
            /** Documents */
            documents: number;
            /** Files */
            files: {
                [key: string]: number;
            };
            /** Quantizer Fitted */
            quantizer_fitted: boolean;
            /** Rescore Multiplier */
            rescore_multiplier: number;
            /** Rows */
            rows: number;
            /** Staged */
            staged: number;
        };
        /** IngestRunView */
        IngestRunView: {
            /** Chunks */
            chunks: number;
            /** Documents */
            documents: number;
            /** Duration Seconds */
            duration_seconds: number;
            /** Error */
            error: string | null;
            /** Skipped Unchanged */
            skipped_unchanged: number;
            /** Started At */
            started_at: string;
            /** Unreadable */
            unreadable: number;
        };
        /** SimulateRequest */
        SimulateRequest: {
            /**
             * Groups
             * @default []
             */
            groups?: string[];
            /**
             * K
             * @default 10
             */
            k?: number;
            /**
             * Limit
             * @default 500
             */
            limit?: number;
            /** Principal */
            principal: string;
            /** Query */
            query?: string | null;
        };
        /** Simulation */
        Simulation: {
            /** Documents */
            documents: components["schemas"]["DocumentDecision"][];
            /** Effective Principals */
            effective_principals: string[];
            /** Principal */
            principal: string;
            /** Results */
            results: {
                [key: string]: unknown;
            } | null;
            /** Total */
            total: number;
            /** Visible Count */
            visible_count: number;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    invalidateAcl: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AclInvalidate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    listConnectors: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConnectorView"][];
                };
            };
        };
    };
    createConnector: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ConnectorCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConnectorView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    deleteConnector: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    ingestConnector: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IngestRunView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    indexHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IndexHealth"];
                };
            };
        };
    };
    simulate: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SimulateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Simulation"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
        };
    };
}
